name: Static Analysis

on: ['pull_request']

concurrency:
  group: static-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  static:
    name: Static Tests

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dependency-version: [prefer-lowest, prefer-stable]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2
        tools: composer:v2
        coverage: none

    - name: Install Dependencies
      run: composer update --prefer-stable --no-interaction --no-progress --ansi

    - name: Types
      run: composer test:types

    - name: Style
      run: composer test:lint
